verbos_basicos_com_significado = [
    ["cook", "She cooks dinner for her family.", "cozinhar"],
    ["clean", "He cleans his room every week.", "limpar"],
    ["wash", "They wash the dishes together.", "lavar"],
    ["cut", "She cuts the paper with scissors.", "cortar"],
    ["brush", "He brushes his teeth every morning.", "escovar"],
    ["comb", "She combs her hair before school.", "pentear"],
    ["dance", "They dance at the party.", "dançar"],
    ["cry", "The baby cries when he is hungry.", "chorar"],
    ["laugh", "She laughs at the funny joke.", "rir"],
    ["smile", "He smiles in the photo.", "sorrir"],
    ["jump", "The kids jump on the trampoline.", "pular"],
    ["run", "He runs fast in the race.", "correr"],
    ["walk", "We walk to the park.", "andar"],
    ["sit", "She sits on the chair.", "sentar"],
    ["stand", "They stand in line for the bus.", "ficar de pé"],
    ["open", "He opens the door for his friend.", "abrir"],
    ["close", "She closes the book after reading.", "fechar"],
    ["turn", "He turns off the light before sleeping.", "virar/desligar"],
    ["hold", "She holds the baby in her arms.", "segurar"],
    ["carry", "He carries his backpack to school.", "carregar"],
    ["pull", "She pulls the door to open it.", "puxar"],
    ["push", "He pushes the shopping cart.", "empurrar"],
    ["throw", "She throws the ball to her friend.", "jogar/lançar"],
    ["catch", "He catches the ball with one hand.", "pegar"],
    ["kick", "She kicks the soccer ball.", "chutar"],
    ["clap", "They clap after the performance.", "aplaudir"],
    ["draw", "He draws a picture of a cat.", "desenhar"],
    ["paint", "She paints a beautiful sunset.", "pintar"],
    ["write", "He writes a letter to his grandmother.", "escrever"],
    ["read", "She reads a book before bed.", "ler"],
    ["listen", "He listens to music while studying.", "ouvir"],
    ["talk", "They talk about their weekend.", "conversar"],
    ["call", "She calls her friend on the phone.", "ligar"],
    ["ask", "He asks a question in class.", "perguntar"],
    ["answer", "She answers the teacher’s question.", "responder"],
    ["help", "He helps his mother in the kitchen.", "ajudar"],
    ["work", "She works at a hospital.", "trabalhar"],
    ["study", "He studies for his exam.", "estudar"],
    ["learn", "She learns a new word every day.", "aprender"],
    ["teach", "He teaches math at school.", "ensinar"],
    ["show", "She shows her drawing to her parents.", "mostrar"],
    ["find", "He finds a coin on the ground.", "encontrar"],
    ["lose", "She loses her keys often.", "perder"],
    ["look", "They look at the beautiful view.", "olhar"],
    ["see", "He sees a bird in the tree.", "ver"],
    ["watch", "She watches TV in the evening.", "assistir"],
    ["buy", "He buys bread at the bakery.", "comprar"],
    ["sell", "She sells flowers at the market.", "vender"],
    ["pay", "He pays for his coffee.", "pagar"],
    ["borrow", "She borrows a book from the library.", "pegar emprestado"],
    ["lend", "He lends his pen to a friend.", "emprestar"],
    ["receive", "She receives a gift on her birthday.", "receber"],
    ["send", "He sends an email to his boss.", "enviar"],
    ["wait", "She waits for the bus.", "esperar"],
    ["need", "He needs a new jacket.", "precisar"],
    ["want", "She wants a piece of cake.", "querer"],
    ["like", "He likes chocolate ice cream.", "gostar"],
    ["love", "She loves her family.", "amar"],
    ["hate", "He hates waking up early.", "odiar"],
    ["enjoy", "She enjoys playing the piano.", "aproveitar"],
    ["live", "He lives in a big city.", "viver/morar"],
    ["visit", "She visits her grandparents on weekends.", "visitar"],
    ["travel", "They travel to different countries.", "viajar"],
    ["arrive", "He arrives at school at 8 AM.", "chegar"],
    ["leave", "She leaves work at 5 PM.", "sair/partir"],
    ["enter", "He enters the classroom quietly.", "entrar"],
    ["exit", "She exits the store after shopping.", "sair"],
    ["stay", "They stay at a hotel during vacations.", "ficar"],
    ["return", "He returns the book to the library.", "devolver/retornar"],
    ["bring", "She brings a cake to the party.", "trazer"],
    ["take", "He takes a photo of the sunset.", "pegar/levar"],
    ["eat", "She eats an apple every morning.", "comer"],
    ["drink", "He drinks water after running.", "beber"],
    ["cook", "She cooks pasta for dinner.", "cozinhar"],
    ["bake", "He bakes a chocolate cake.", "assar"],
    ["taste", "She tastes the soup to check the flavor.", "provar"],
    ["smell", "He smells the fresh flowers.", "cheirar"],
    ["touch", "She touches the soft fabric.", "tocar"],
    ["feel", "He feels happy today.", "sentir"],
    ["hear", "She hears the birds singing.", "ouvir"],
    ["wake up", "He wakes up at 7 AM.", "acordar"],
    ["sleep", "She sleeps for eight hours.", "dormir"],
    ["dream", "He dreams about flying.", "sonhar"],
    ["rest", "She rests after a long day.", "descansar"],
    ["exercise", "He exercises every morning.", "fazer exercícios"],
    ["stretch", "She stretches before running.", "alongar"],
    ["yawn", "He yawns when he is sleepy.", "bocejar"],
    ["sneeze", "She sneezes because of allergies.", "espirrar"],
    ["cough", "He coughs when he is sick.", "tossir"],
    ["climb", "She climbs the stairs quickly.", "subir/escalar"],
    ["swim", "He swims in the pool.", "nadar"],
    ["fly", "The bird flies in the sky.", "voar"],
    ["ride", "She rides her bicycle to school.", "andar de (bike/cavalo)"],
    ["fix", "He fixes his broken chair.", "consertar"],
    ["build", "She builds a sandcastle.", "construir"],
    ["break", "He breaks his phone screen.", "quebrar"],
    ["change", "She changes her clothes.", "mudar"],
    ["use", "He uses a computer for work.", "usar"],
    ["share", "She shares her snacks with friends.", "compartilhar"],
    ["keep", "He keeps his room clean.", "manter"],
    ["choose", "She chooses a red dress.", "escolher"]
]



verbos_intermediarios_com_significado = [
    ["think", "I think about my future a lot.", "pensar"],
    ["believe", "She believes in herself.", "acreditar"],
    ["hope", "I hope you have a great day.", "esperar/ter esperança"],
    ["know", "They know the answer.", "saber"],
    ["understand", "He understands the lesson well.", "entender"],
    ["remember", "She remembers her childhood.", "lembrar"],
    ["forget", "I always forget my keys.", "esquecer"],
    ["learn", "We learn something new every day.", "aprender"],
    ["teach", "He teaches English at a school.", "ensinar"],
    ["show", "Can you show me the way?", "mostrar"],
    ["find", "She finds her lost phone.", "encontrar"],
    ["lose", "I lost my wallet yesterday.", "perder"],
    ["win", "They won the championship!", "vencer"],
    ["spend", "I spend a lot of time reading.", "gastar (tempo/dinheiro)"],
    ["save", "She saves money for a trip.", "economizar/salvar"],
    ["borrow", "Can I borrow your book?", "pegar emprestado"],
    ["lend", "I will lend you my pen.", "emprestar"],
    ["send", "She sends an email every morning.", "enviar"],
    ["receive", "He received a gift from his friend.", "receber"],
    ["ask", "I ask questions in class.", "perguntar"],
    ["answer", "She answers all the questions correctly.", "responder"],
    ["help", "They help their parents at home.", "ajudar"],
    ["fix", "He fixes his broken bike.", "consertar"],
    ["build", "They build houses for the poor.", "construir"],
    ["break", "I broke my phone screen.", "quebrar"],
    ["cut", "She cuts the paper with scissors.", "cortar"],
    ["paint", "He paints beautiful landscapes.", "pintar"],
    ["draw", "She draws a picture of a cat.", "desenhar"],
    ["meet", "We meet our friends at the mall.", "encontrar-se/conhecer"],
    ["invite", "I invite them to my party.", "convidar"],
    ["call", "She calls her mother every day.", "ligar/chamar"],
    ["wait", "They wait for the bus.", "esperar"],
    ["start", "The meeting starts at 9 a.m.", "começar"],
    ["finish", "I finish my homework before dinner.", "terminar"],
    ["continue", "He continues his studies abroad.", "continuar"],
    ["try", "She tries to learn French.", "tentar"],
    ["choose", "They choose a restaurant.", "escolher"],
    ["prefer", "I prefer coffee over tea.", "preferir"],
    ["need", "She needs a break.", "precisar"],
    ["exist", "Life exists on Earth.", "existir"],
    ["fall", "The leaves fall in autumn.", "cair"],
    ["stand", "They stand in line.", "ficar de pé"],
    ["sit", "She sits on the couch.", "sentar"],
    ["lie", "He lies on the bed.", "deitar"],
    ["turn", "She turns the page of the book.", "virar"],
    ["move", "They move to a new house.", "mudar/movimentar"],
    ["push", "He pushes the door open.", "empurrar"],
    ["pull", "She pulls the rope.", "puxar"],
    ["carry", "I carry my backpack to school.", "carregar"],
    ["throw", "He throws the ball to me.", "jogar/lancar"],
    ["catch", "She catches the ball easily.", "pegar"],
    ["hit", "He hits the ball with a bat.", "bater"],
    ["kick", "She kicks the ball into the goal.", "chutar"],
    ["climb", "They climb the mountain.", "escalar"],
    ["swim", "He swims in the pool.", "nadar"],
    ["fly", "The bird flies in the sky.", "voar"],
    ["drive", "She drives to work every day.", "dirigir"],
    ["ride", "He rides his bike to school.", "andar de (bike/cavalo)"],
    ["follow", "They follow the leader.", "seguir"],
    ["lead", "She leads the team to victory.", "liderar"],
    ["allow", "They allow pets in the park.", "permitir"],
    ["forbid", "The school forbids smoking.", "proibir"],
    ["agree", "I agree with your opinion.", "concordar"],
    ["disagree", "She disagrees with the decision.", "discordar"],
    ["promise", "He promises to come back.", "prometer"],
    ["refuse", "She refuses to answer.", "recusar"],
    ["apologize", "They apologize for the mistake.", "pedir desculpa"],
    ["thank", "I thank you for your help.", "agradecer"],
    ["complain", "He complains about the noise.", "reclamar"],
    ["whisper", "She whispers a secret.", "sussurrar"],
    ["shout", "They shout at the concert.", "gritar"],
    ["laugh", "He laughs at the joke.", "rir"],
    ["cry", "She cries during the movie.", "chorar"],
    ["smile", "They smile for the photo.", "sorrir"],
    ["dream", "I dream about traveling.", "sonhar"],
    ["wish", "She wishes for a better future.", "desejar"],
    ["grow", "The plants grow in the garden.", "crescer"],
    ["change", "He changes his clothes.", "mudar"],
    ["break up", "They broke up last year.", "terminar relacionamento"],
    ["marry", "She marries her best friend.", "casar"],
    ["divorce", "They divorced after ten years.", "divorciar"],
    ["care", "She cares about her friends.", "se importar"],
    ["respect", "They respect their teacher.", "respeitar"],
    ["trust", "He trusts his best friend.", "confiar"],
    ["doubt", "She doubts his story.", "duvidar"],
    ["fear", "He fears the dark.", "temer"],
    ["hate", "They hate waiting in line.", "odiar"],
    ["enjoy", "I enjoy watching movies.", "aproveitar"],
    ["celebrate", "They celebrate their anniversary.", "celebrar"],
    ["cook", "She cooks dinner for her family.", "cozinhar"],
    ["clean", "He cleans his room every week.", "limpar"],
    ["wash", "They wash the dishes together.", "lavar"],
    ["iron", "She irons her clothes.", "passar roupa"],
    ["sweep", "He sweeps the floor.", "varrer"],
    ["sew", "She sews a dress.", "costurar"],
    ["measure", "He measures the table.", "medir"],
    ["count", "She counts the money.", "contar (números)"],
    ["spell", "He spells his name correctly.", "soletrar"],
    ["translate", "She translates the text.", "traduzir"]
]


verbos_avancados_com_significado = [
    ["achieve", "She achieved her goals with hard work.", "alcançar"],
    ["convince", "He convinced me to go to the party.", "convencer"],
    ["neglect", "They neglected their responsibilities.", "negligenciar"],
    ["overcome", "She overcame her fear of public speaking.", "superar"],
    ["acknowledge", "He acknowledged his mistake.", "reconhecer"],
    ["endure", "They endured many difficulties.", "suportar/endurecer"],
    ["enhance", "This program enhances productivity.", "melhorar"],
    ["reconsider", "I will reconsider your proposal.", "reconsiderar"],
    ["justify", "He justified his actions to the manager.", "justificar"],
    ["portray", "The movie portrays the life of a famous artist.", "retratar"],
    ["criticize", "She criticized the new law.", "criticar"],
    ["emphasize", "He emphasized the importance of teamwork.", "enfatizar"],
    ["underestimate", "They underestimated the difficulty of the task.", "subestimar"],
    ["overestimate", "She overestimated his abilities.", "superestimar"],
    ["clarify", "He clarified his point during the meeting.", "esclarecer"],
    ["analyze", "They analyzed the market trends.", "analisar"],
    ["interpret", "She interpreted the poem beautifully.", "interpretar"],
    ["formulate", "He formulated a new hypothesis.", "formular"],
    ["execute", "The team executed the plan perfectly.", "executar"],
    ["delegate", "She delegated tasks to her team.", "delegar"],
    ["innovate", "The company innovates every year.", "inovar"],
    ["anticipate", "He anticipated the problem before it happened.", "antecipar"],
    ["manipulate", "They manipulated the data to fit their narrative.", "manipular"],
    ["assess", "She assessed the student's progress.", "avaliar"],
    ["prioritize", "He prioritizes his work over leisure.", "priorizar"],
    ["reinforce", "They reinforced the building’s structure.", "reforçar"],
    ["synthesize", "She synthesized the information into a summary.", "sintetizar"],
    ["scrutinize", "The scientist scrutinized the results.", "examinar cuidadosamente"],
    ["mitigate", "The new policy mitigates the risks.", "mitigar"],
    ["accelerate", "The company accelerated its production.", "acelerar"],
    ["absorb", "The sponge absorbs water quickly.", "absorver"],
    ["adapt", "She adapted to the new environment.", "adaptar"],
    ["administer", "He administers the financial department.", "administrar"],
    ["advocate", "She advocates for human rights.", "defender"],
    ["allocate", "They allocated funds for education.", "alocar"],
    ["alleviate", "The medicine alleviates pain.", "aliviar"],
    ["amplify", "The speaker amplified his voice.", "ampliar"],
    ["anticipate", "She anticipated the question and prepared an answer.", "antecipar"],
    ["articulate", "He articulated his ideas clearly.", "articular"],
    ["assert", "She asserted her authority in the meeting.", "afirmar"],
    ["attain", "He attained a high level of success.", "atingir"],
    ["authorize", "The manager authorized the purchase.", "autorizar"],
    ["compile", "They compiled a list of important documents.", "compilar"],
    ["conceive", "She conceived a brilliant plan.", "conceber"],
    ["condemn", "The public condemned the politician’s actions.", "condenar"],
    ["conform", "He conformed to the company’s rules.", "conformar-se"],
    ["constrain", "Time constraints limited our options.", "restringir"],
    ["contaminate", "The river was contaminated by chemicals.", "contaminar"],
    ["contrast", "Her opinion contrasts with his.", "contrastar"],
    ["convey", "He conveyed his message clearly.", "transmitir"],
    ["coordinate", "She coordinated the event successfully.", "coordenar"],
    ["correlate", "The study correlates diet with health.", "correlacionar"],
    ["decrease", "Sales decreased last month.", "diminuir"],
    ["dedicate", "She dedicated her life to science.", "dedicar"],
    ["defy", "They defied the rules.", "desafiar"],
    ["deprive", "He was deprived of his rights.", "privar"],
    ["detect", "The scientist detected a new virus.", "detectar"],
    ["dictate", "The boss dictated the rules to the employees.", "ditar"],
    ["differentiate", "She differentiates between right and wrong.", "diferenciar"],
    ["discern", "He discerned a hidden meaning in the text.", "discernir"],
    ["disclose", "The report disclosed new information.", "revelar"],
    ["disrupt", "The protest disrupted traffic.", "interromper"],
    ["distort", "The media distorted the facts.", "distorcer"],
    ["elaborate", "He elaborated on his plan.", "elaborar"],
    ["eliminate", "They eliminated all errors from the report.", "eliminar"],
    ["empower", "The program empowers young entrepreneurs.", "capacitar"],
    ["enforce", "The police enforce the law.", "aplicar"],
    ["enrich", "Traveling enriches our perspective.", "enriquecer"],
    ["entail", "This job entails a lot of responsibility.", "implicar"],
    ["eradicate", "They aim to eradicate poverty.", "erradicar"],
    ["evaluate", "The teacher evaluated the students’ performance.", "avaliar"],
    ["exceed", "Sales exceeded expectations.", "exceder"],
    ["exploit", "The company exploited natural resources.", "explorar"],
    ["facilitate", "The new software facilitates communication.", "facilitar"],
    ["foster", "The teacher fosters creativity in students.", "fomentar"],
    ["generate", "The company generates electricity.", "gerar"],
    ["hinder", "The rain hindered our travel plans.", "impedir"],
    ["illuminate", "The streetlights illuminate the road.", "iluminar"],
    ["immerse", "She immersed herself in her studies.", "imergir"],
    ["imply", "His tone implied anger.", "implicar"],
    ["induce", "The medication induced sleep.", "induzir"],
    ["inflict", "The war inflicted great suffering.", "infligir"],
    ["instigate", "The speech instigated a reaction.", "instigar"],
    ["integrate", "The immigrants integrated into society.", "integrar"],
    ["intervene", "The doctor intervened in the emergency.", "intervir"],
    ["invalidate", "The error invalidated the results.", "invalidar"],
    ["jeopardize", "The scandal jeopardized his career.", "colocar em risco"],
    ["manifest", "His anger manifested in his words.", "manifestar"],
    ["mediate", "She mediated the conflict.", "mediar"],
    ["moderate", "The teacher moderated the debate.", "moderar"],
    ["negate", "The new evidence negates the previous theory.", "negar"],
    ["optimize", "They optimized the process for efficiency.", "otimizar"],
    ["perceive", "She perceived a change in his behavior.", "perceber"],
    ["preserve", "The museum preserves historical artifacts.", "preservar"],
    ["prohibit", "The law prohibits smoking in public places.", "proibir"],
    ["rectify", "The mistake was rectified quickly.", "corrigir"],
    ["regulate", "The government regulates the economy.", "regular"],
    ["safeguard", "The policy safeguards human rights.", "proteger"],
    ["streamline", "The company streamlined its operations.", "simplificar"],
    ["substantiate", "The scientist substantiated his claims with evidence.", "comprovar"],
    ["withstand", "The building withstands strong winds.", "resistir"]
]



def searchWord(num_lista,num_palabra):

    global verbos_basicos_com_significado
    global verbos_intermediarios_com_significado
    global verbos_avancados_com_significado

    if num_lista == 0:
        inventory = verbos_basicos_com_significado

    elif num_lista == 1:
        inventory = verbos_intermediarios_com_significado

    else:
        inventory = verbos_avancados_com_significado

    inventory = inventory[num_palabra-1]

    return inventory

